# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the OS and Python version
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

# Build documentation with MkDocs
mkdocs:
  configuration: mkdocs.yml
  fail_on_warning: false
  strict: false

# Python requirements for building docs
python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
    - path: .

# Output formats
formats:
  - pdf
  - epub
  - htmlzip 